// Code generated by MockGen. DO NOT EDIT.
// Source: mongo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MockMongoCollectionInterface is a mock of MongoCollectionInterface interface.
type MockMongoCollectionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMongoCollectionInterfaceMockRecorder
}

// MockMongoCollectionInterfaceMockRecorder is the mock recorder for MockMongoCollectionInterface.
type MockMongoCollectionInterfaceMockRecorder struct {
	mock *MockMongoCollectionInterface
}

// NewMockMongoCollectionInterface creates a new mock instance.
func NewMockMongoCollectionInterface(ctrl *gomock.Controller) *MockMongoCollectionInterface {
	mock := &MockMongoCollectionInterface{ctrl: ctrl}
	mock.recorder = &MockMongoCollectionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoCollectionInterface) EXPECT() *MockMongoCollectionInterfaceMockRecorder {
	return m.recorder
}

// FindOne mocks base method.
func (m *MockMongoCollectionInterface) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) *mongo.SingleResult {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*mongo.SingleResult)
	return ret0
}

// FindOne indicates an expected call of FindOne.
func (mr *MockMongoCollectionInterfaceMockRecorder) FindOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockMongoCollectionInterface)(nil).FindOne), varargs...)
}

// InsertOne mocks base method.
func (m *MockMongoCollectionInterface) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, document}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockMongoCollectionInterfaceMockRecorder) InsertOne(ctx, document interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, document}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockMongoCollectionInterface)(nil).InsertOne), varargs...)
}
