// Code generated by MockGen. DO NOT EDIT.
// Source: account_recover.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountRecoverStorage is a mock of AccountRecoverStorage interface.
type MockAccountRecoverStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRecoverStorageMockRecorder
}

// MockAccountRecoverStorageMockRecorder is the mock recorder for MockAccountRecoverStorage.
type MockAccountRecoverStorageMockRecorder struct {
	mock *MockAccountRecoverStorage
}

// NewMockAccountRecoverStorage creates a new mock instance.
func NewMockAccountRecoverStorage(ctrl *gomock.Controller) *MockAccountRecoverStorage {
	mock := &MockAccountRecoverStorage{ctrl: ctrl}
	mock.recorder = &MockAccountRecoverStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRecoverStorage) EXPECT() *MockAccountRecoverStorageMockRecorder {
	return m.recorder
}

// RetriveAccountRecoveryKey mocks base method.
func (m *MockAccountRecoverStorage) RetriveAccountRecoveryKey(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetriveAccountRecoveryKey", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetriveAccountRecoveryKey indicates an expected call of RetriveAccountRecoveryKey.
func (mr *MockAccountRecoverStorageMockRecorder) RetriveAccountRecoveryKey(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetriveAccountRecoveryKey", reflect.TypeOf((*MockAccountRecoverStorage)(nil).RetriveAccountRecoveryKey), ctx, userID)
}

// StoreAccountRecoveryKey mocks base method.
func (m *MockAccountRecoverStorage) StoreAccountRecoveryKey(ctx context.Context, userID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAccountRecoveryKey", ctx, userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAccountRecoveryKey indicates an expected call of StoreAccountRecoveryKey.
func (mr *MockAccountRecoverStorageMockRecorder) StoreAccountRecoveryKey(ctx, userID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAccountRecoveryKey", reflect.TypeOf((*MockAccountRecoverStorage)(nil).StoreAccountRecoveryKey), ctx, userID, code)
}
