// Code generated by MockGen. DO NOT EDIT.
// Source: documents.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "ishkul.org/backend/model"
)

// MockDocumentDatabase is a mock of DocumentDatabase interface.
type MockDocumentDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentDatabaseMockRecorder
}

// MockDocumentDatabaseMockRecorder is the mock recorder for MockDocumentDatabase.
type MockDocumentDatabaseMockRecorder struct {
	mock *MockDocumentDatabase
}

// NewMockDocumentDatabase creates a new mock instance.
func NewMockDocumentDatabase(ctrl *gomock.Controller) *MockDocumentDatabase {
	mock := &MockDocumentDatabase{ctrl: ctrl}
	mock.recorder = &MockDocumentDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentDatabase) EXPECT() *MockDocumentDatabaseMockRecorder {
	return m.recorder
}

// AddDocument mocks base method.
func (m *MockDocumentDatabase) AddDocument(ctx context.Context, documents []model.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDocument", ctx, documents)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDocument indicates an expected call of AddDocument.
func (mr *MockDocumentDatabaseMockRecorder) AddDocument(ctx, documents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDocument", reflect.TypeOf((*MockDocumentDatabase)(nil).AddDocument), ctx, documents)
}

// FindDocumentByID mocks base method.
func (m *MockDocumentDatabase) FindDocumentByID(ctx context.Context, id string) (model.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDocumentByID", ctx, id)
	ret0, _ := ret[0].(model.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDocumentByID indicates an expected call of FindDocumentByID.
func (mr *MockDocumentDatabaseMockRecorder) FindDocumentByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDocumentByID", reflect.TypeOf((*MockDocumentDatabase)(nil).FindDocumentByID), ctx, id)
}

// GetDocuments mocks base method.
func (m *MockDocumentDatabase) GetDocuments(ctx context.Context) ([]model.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocuments", ctx)
	ret0, _ := ret[0].([]model.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocuments indicates an expected call of GetDocuments.
func (mr *MockDocumentDatabaseMockRecorder) GetDocuments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocuments", reflect.TypeOf((*MockDocumentDatabase)(nil).GetDocuments), ctx)
}

// SearchDocument mocks base method.
func (m *MockDocumentDatabase) SearchDocument(ctx context.Context, query string) ([]model.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDocument", ctx, query)
	ret0, _ := ret[0].([]model.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDocument indicates an expected call of SearchDocument.
func (mr *MockDocumentDatabaseMockRecorder) SearchDocument(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDocument", reflect.TypeOf((*MockDocumentDatabase)(nil).SearchDocument), ctx, query)
}

// MockDocumentLimitStorage is a mock of DocumentLimitStorage interface.
type MockDocumentLimitStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentLimitStorageMockRecorder
}

// MockDocumentLimitStorageMockRecorder is the mock recorder for MockDocumentLimitStorage.
type MockDocumentLimitStorageMockRecorder struct {
	mock *MockDocumentLimitStorage
}

// NewMockDocumentLimitStorage creates a new mock instance.
func NewMockDocumentLimitStorage(ctrl *gomock.Controller) *MockDocumentLimitStorage {
	mock := &MockDocumentLimitStorage{ctrl: ctrl}
	mock.recorder = &MockDocumentLimitStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentLimitStorage) EXPECT() *MockDocumentLimitStorageMockRecorder {
	return m.recorder
}

// IncrUserResourceRequest mocks base method.
func (m *MockDocumentLimitStorage) IncrUserResourceRequest(ctx context.Context, endpoint, userID string, limit int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrUserResourceRequest", ctx, endpoint, userID, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrUserResourceRequest indicates an expected call of IncrUserResourceRequest.
func (mr *MockDocumentLimitStorageMockRecorder) IncrUserResourceRequest(ctx, endpoint, userID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrUserResourceRequest", reflect.TypeOf((*MockDocumentLimitStorage)(nil).IncrUserResourceRequest), ctx, endpoint, userID, limit)
}
