// Code generated by MockGen. DO NOT EDIT.
// Source: send_verification_code.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountStorage is a mock of AccountStorage interface.
type MockAccountStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAccountStorageMockRecorder
}

// MockAccountStorageMockRecorder is the mock recorder for MockAccountStorage.
type MockAccountStorageMockRecorder struct {
	mock *MockAccountStorage
}

// NewMockAccountStorage creates a new mock instance.
func NewMockAccountStorage(ctrl *gomock.Controller) *MockAccountStorage {
	mock := &MockAccountStorage{ctrl: ctrl}
	mock.recorder = &MockAccountStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountStorage) EXPECT() *MockAccountStorageMockRecorder {
	return m.recorder
}

// RemoveAccountRecoveryKey mocks base method.
func (m *MockAccountStorage) RemoveAccountRecoveryKey(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccountRecoveryKey", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAccountRecoveryKey indicates an expected call of RemoveAccountRecoveryKey.
func (mr *MockAccountStorageMockRecorder) RemoveAccountRecoveryKey(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccountRecoveryKey", reflect.TypeOf((*MockAccountStorage)(nil).RemoveAccountRecoveryKey), ctx, userID)
}

// RetriveAccountRecoveryKey mocks base method.
func (m *MockAccountStorage) RetriveAccountRecoveryKey(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetriveAccountRecoveryKey", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetriveAccountRecoveryKey indicates an expected call of RetriveAccountRecoveryKey.
func (mr *MockAccountStorageMockRecorder) RetriveAccountRecoveryKey(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetriveAccountRecoveryKey", reflect.TypeOf((*MockAccountStorage)(nil).RetriveAccountRecoveryKey), ctx, userID)
}

// StoreAccountRecoveryKey mocks base method.
func (m *MockAccountStorage) StoreAccountRecoveryKey(ctx context.Context, userID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAccountRecoveryKey", ctx, userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAccountRecoveryKey indicates an expected call of StoreAccountRecoveryKey.
func (mr *MockAccountStorageMockRecorder) StoreAccountRecoveryKey(ctx, userID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAccountRecoveryKey", reflect.TypeOf((*MockAccountStorage)(nil).StoreAccountRecoveryKey), ctx, userID, code)
}
