/**
 * Firebase Auth Service
 *
 * Handles Firebase authentication using custom tokens from the backend.
 * This enables real-time Firestore subscriptions with proper security.
 */

import { signInWithCustomToken, signOut, User, onAuthStateChanged } from 'firebase/auth';
import { getFirebaseAuth } from './index';

/**
 * Sign in to Firebase using a custom token from the backend
 * @param customToken - The Firebase custom token generated by the backend
 * @returns The Firebase User object
 */
export async function signInWithFirebaseToken(customToken: string): Promise<User> {
  const auth = getFirebaseAuth();
  const userCredential = await signInWithCustomToken(auth, customToken);
  return userCredential.user;
}

/**
 * Sign out from Firebase
 * Should be called when the user logs out of the app
 */
export async function signOutFromFirebase(): Promise<void> {
  const auth = getFirebaseAuth();
  await signOut(auth);
}

/**
 * Get the current Firebase user (if authenticated)
 */
export function getCurrentFirebaseUser(): User | null {
  const auth = getFirebaseAuth();
  return auth.currentUser;
}

/**
 * Check if the user is authenticated with Firebase
 */
export function isFirebaseAuthenticated(): boolean {
  return getCurrentFirebaseUser() !== null;
}

/**
 * Subscribe to Firebase auth state changes
 * @param callback - Function called when auth state changes
 * @returns Unsubscribe function
 */
export function onFirebaseAuthStateChanged(
  callback: (user: User | null) => void
): () => void {
  const auth = getFirebaseAuth();
  return onAuthStateChanged(auth, callback);
}

/**
 * Get Firebase ID token for the current user
 * Useful for debugging or if needed for API calls
 */
export async function getFirebaseIdToken(): Promise<string | null> {
  const user = getCurrentFirebaseUser();
  if (!user) {
    return null;
  }
  return user.getIdToken();
}
